/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuitamanyRouteRouteImport } from './routes/_authenticated/quitamany/route'
import { Route as AuthenticatedPublicadorRouteRouteImport } from './routes/_authenticated/publicador/route'
import { Route as AuthenticatedQuitamanyIndexRouteImport } from './routes/_authenticated/quitamany/index'
import { Route as AuthenticatedPublicadorIndexRouteImport } from './routes/_authenticated/publicador/index'
import { Route as ApiPublicMetaCallbackRouteImport } from './routes/api/public/meta-callback'
import { Route as AuthenticatedQuitamanyContatosRouteImport } from './routes/_authenticated/quitamany/contatos'
import { Route as AuthenticatedQuitamanyAutomacoesRouteImport } from './routes/_authenticated/quitamany/automacoes'
import { Route as AuthenticatedQuitamanyAjustesRouteImport } from './routes/_authenticated/quitamany/ajustes'
import { Route as AuthenticatedPublicadorNovoRouteImport } from './routes/_authenticated/publicador/novo'
import { Route as AuthenticatedPublicadorHistoricoRouteImport } from './routes/_authenticated/publicador/historico'
import { Route as AuthenticatedPublicadorAjustesRouteImport } from './routes/_authenticated/publicador/ajustes'
import { Route as ApiPublicHooksWebhookInstagramRouteImport } from './routes/api/public/hooks/webhook-instagram'
import { Route as ApiPublicHooksRenovarTokensRouteImport } from './routes/api/public/hooks/renovar-tokens'
import { Route as ApiPublicHooksPublicarPostsRouteImport } from './routes/api/public/hooks/publicar-posts'
import { Route as AuthenticatedQuitamanyConversaIdRouteImport } from './routes/_authenticated/quitamany/conversa.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuitamanyRouteRoute =
  AuthenticatedQuitamanyRouteRouteImport.update({
    id: '/quitamany',
    path: '/quitamany',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPublicadorRouteRoute =
  AuthenticatedPublicadorRouteRouteImport.update({
    id: '/publicador',
    path: '/publicador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuitamanyIndexRoute =
  AuthenticatedQuitamanyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedQuitamanyRouteRoute,
  } as any)
const AuthenticatedPublicadorIndexRoute =
  AuthenticatedPublicadorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPublicadorRouteRoute,
  } as any)
const ApiPublicMetaCallbackRoute = ApiPublicMetaCallbackRouteImport.update({
  id: '/api/public/meta-callback',
  path: '/api/public/meta-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuitamanyContatosRoute =
  AuthenticatedQuitamanyContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => AuthenticatedQuitamanyRouteRoute,
  } as any)
const AuthenticatedQuitamanyAutomacoesRoute =
  AuthenticatedQuitamanyAutomacoesRouteImport.update({
    id: '/automacoes',
    path: '/automacoes',
    getParentRoute: () => AuthenticatedQuitamanyRouteRoute,
  } as any)
const AuthenticatedQuitamanyAjustesRoute =
  AuthenticatedQuitamanyAjustesRouteImport.update({
    id: '/ajustes',
    path: '/ajustes',
    getParentRoute: () => AuthenticatedQuitamanyRouteRoute,
  } as any)
const AuthenticatedPublicadorNovoRoute =
  AuthenticatedPublicadorNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedPublicadorRouteRoute,
  } as any)
const AuthenticatedPublicadorHistoricoRoute =
  AuthenticatedPublicadorHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedPublicadorRouteRoute,
  } as any)
const AuthenticatedPublicadorAjustesRoute =
  AuthenticatedPublicadorAjustesRouteImport.update({
    id: '/ajustes',
    path: '/ajustes',
    getParentRoute: () => AuthenticatedPublicadorRouteRoute,
  } as any)
const ApiPublicHooksWebhookInstagramRoute =
  ApiPublicHooksWebhookInstagramRouteImport.update({
    id: '/api/public/hooks/webhook-instagram',
    path: '/api/public/hooks/webhook-instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRenovarTokensRoute =
  ApiPublicHooksRenovarTokensRouteImport.update({
    id: '/api/public/hooks/renovar-tokens',
    path: '/api/public/hooks/renovar-tokens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublicarPostsRoute =
  ApiPublicHooksPublicarPostsRouteImport.update({
    id: '/api/public/hooks/publicar-posts',
    path: '/api/public/hooks/publicar-posts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedQuitamanyConversaIdRoute =
  AuthenticatedQuitamanyConversaIdRouteImport.update({
    id: '/conversa/$id',
    path: '/conversa/$id',
    getParentRoute: () => AuthenticatedQuitamanyRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/publicador': typeof AuthenticatedPublicadorRouteRouteWithChildren
  '/quitamany': typeof AuthenticatedQuitamanyRouteRouteWithChildren
  '/publicador/ajustes': typeof AuthenticatedPublicadorAjustesRoute
  '/publicador/historico': typeof AuthenticatedPublicadorHistoricoRoute
  '/publicador/novo': typeof AuthenticatedPublicadorNovoRoute
  '/quitamany/ajustes': typeof AuthenticatedQuitamanyAjustesRoute
  '/quitamany/automacoes': typeof AuthenticatedQuitamanyAutomacoesRoute
  '/quitamany/contatos': typeof AuthenticatedQuitamanyContatosRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/publicador/': typeof AuthenticatedPublicadorIndexRoute
  '/quitamany/': typeof AuthenticatedQuitamanyIndexRoute
  '/quitamany/conversa/$id': typeof AuthenticatedQuitamanyConversaIdRoute
  '/api/public/hooks/publicar-posts': typeof ApiPublicHooksPublicarPostsRoute
  '/api/public/hooks/renovar-tokens': typeof ApiPublicHooksRenovarTokensRoute
  '/api/public/hooks/webhook-instagram': typeof ApiPublicHooksWebhookInstagramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/publicador/ajustes': typeof AuthenticatedPublicadorAjustesRoute
  '/publicador/historico': typeof AuthenticatedPublicadorHistoricoRoute
  '/publicador/novo': typeof AuthenticatedPublicadorNovoRoute
  '/quitamany/ajustes': typeof AuthenticatedQuitamanyAjustesRoute
  '/quitamany/automacoes': typeof AuthenticatedQuitamanyAutomacoesRoute
  '/quitamany/contatos': typeof AuthenticatedQuitamanyContatosRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/publicador': typeof AuthenticatedPublicadorIndexRoute
  '/quitamany': typeof AuthenticatedQuitamanyIndexRoute
  '/quitamany/conversa/$id': typeof AuthenticatedQuitamanyConversaIdRoute
  '/api/public/hooks/publicar-posts': typeof ApiPublicHooksPublicarPostsRoute
  '/api/public/hooks/renovar-tokens': typeof ApiPublicHooksRenovarTokensRoute
  '/api/public/hooks/webhook-instagram': typeof ApiPublicHooksWebhookInstagramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/publicador': typeof AuthenticatedPublicadorRouteRouteWithChildren
  '/_authenticated/quitamany': typeof AuthenticatedQuitamanyRouteRouteWithChildren
  '/_authenticated/publicador/ajustes': typeof AuthenticatedPublicadorAjustesRoute
  '/_authenticated/publicador/historico': typeof AuthenticatedPublicadorHistoricoRoute
  '/_authenticated/publicador/novo': typeof AuthenticatedPublicadorNovoRoute
  '/_authenticated/quitamany/ajustes': typeof AuthenticatedQuitamanyAjustesRoute
  '/_authenticated/quitamany/automacoes': typeof AuthenticatedQuitamanyAutomacoesRoute
  '/_authenticated/quitamany/contatos': typeof AuthenticatedQuitamanyContatosRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/_authenticated/publicador/': typeof AuthenticatedPublicadorIndexRoute
  '/_authenticated/quitamany/': typeof AuthenticatedQuitamanyIndexRoute
  '/_authenticated/quitamany/conversa/$id': typeof AuthenticatedQuitamanyConversaIdRoute
  '/api/public/hooks/publicar-posts': typeof ApiPublicHooksPublicarPostsRoute
  '/api/public/hooks/renovar-tokens': typeof ApiPublicHooksRenovarTokensRoute
  '/api/public/hooks/webhook-instagram': typeof ApiPublicHooksWebhookInstagramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/publicador'
    | '/quitamany'
    | '/publicador/ajustes'
    | '/publicador/historico'
    | '/publicador/novo'
    | '/quitamany/ajustes'
    | '/quitamany/automacoes'
    | '/quitamany/contatos'
    | '/api/public/meta-callback'
    | '/publicador/'
    | '/quitamany/'
    | '/quitamany/conversa/$id'
    | '/api/public/hooks/publicar-posts'
    | '/api/public/hooks/renovar-tokens'
    | '/api/public/hooks/webhook-instagram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/publicador/ajustes'
    | '/publicador/historico'
    | '/publicador/novo'
    | '/quitamany/ajustes'
    | '/quitamany/automacoes'
    | '/quitamany/contatos'
    | '/api/public/meta-callback'
    | '/publicador'
    | '/quitamany'
    | '/quitamany/conversa/$id'
    | '/api/public/hooks/publicar-posts'
    | '/api/public/hooks/renovar-tokens'
    | '/api/public/hooks/webhook-instagram'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/publicador'
    | '/_authenticated/quitamany'
    | '/_authenticated/publicador/ajustes'
    | '/_authenticated/publicador/historico'
    | '/_authenticated/publicador/novo'
    | '/_authenticated/quitamany/ajustes'
    | '/_authenticated/quitamany/automacoes'
    | '/_authenticated/quitamany/contatos'
    | '/api/public/meta-callback'
    | '/_authenticated/publicador/'
    | '/_authenticated/quitamany/'
    | '/_authenticated/quitamany/conversa/$id'
    | '/api/public/hooks/publicar-posts'
    | '/api/public/hooks/renovar-tokens'
    | '/api/public/hooks/webhook-instagram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMetaCallbackRoute: typeof ApiPublicMetaCallbackRoute
  ApiPublicHooksPublicarPostsRoute: typeof ApiPublicHooksPublicarPostsRoute
  ApiPublicHooksRenovarTokensRoute: typeof ApiPublicHooksRenovarTokensRoute
  ApiPublicHooksWebhookInstagramRoute: typeof ApiPublicHooksWebhookInstagramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quitamany': {
      id: '/_authenticated/quitamany'
      path: '/quitamany'
      fullPath: '/quitamany'
      preLoaderRoute: typeof AuthenticatedQuitamanyRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publicador': {
      id: '/_authenticated/publicador'
      path: '/publicador'
      fullPath: '/publicador'
      preLoaderRoute: typeof AuthenticatedPublicadorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quitamany/': {
      id: '/_authenticated/quitamany/'
      path: '/'
      fullPath: '/quitamany/'
      preLoaderRoute: typeof AuthenticatedQuitamanyIndexRouteImport
      parentRoute: typeof AuthenticatedQuitamanyRouteRoute
    }
    '/_authenticated/publicador/': {
      id: '/_authenticated/publicador/'
      path: '/'
      fullPath: '/publicador/'
      preLoaderRoute: typeof AuthenticatedPublicadorIndexRouteImport
      parentRoute: typeof AuthenticatedPublicadorRouteRoute
    }
    '/api/public/meta-callback': {
      id: '/api/public/meta-callback'
      path: '/api/public/meta-callback'
      fullPath: '/api/public/meta-callback'
      preLoaderRoute: typeof ApiPublicMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quitamany/contatos': {
      id: '/_authenticated/quitamany/contatos'
      path: '/contatos'
      fullPath: '/quitamany/contatos'
      preLoaderRoute: typeof AuthenticatedQuitamanyContatosRouteImport
      parentRoute: typeof AuthenticatedQuitamanyRouteRoute
    }
    '/_authenticated/quitamany/automacoes': {
      id: '/_authenticated/quitamany/automacoes'
      path: '/automacoes'
      fullPath: '/quitamany/automacoes'
      preLoaderRoute: typeof AuthenticatedQuitamanyAutomacoesRouteImport
      parentRoute: typeof AuthenticatedQuitamanyRouteRoute
    }
    '/_authenticated/quitamany/ajustes': {
      id: '/_authenticated/quitamany/ajustes'
      path: '/ajustes'
      fullPath: '/quitamany/ajustes'
      preLoaderRoute: typeof AuthenticatedQuitamanyAjustesRouteImport
      parentRoute: typeof AuthenticatedQuitamanyRouteRoute
    }
    '/_authenticated/publicador/novo': {
      id: '/_authenticated/publicador/novo'
      path: '/novo'
      fullPath: '/publicador/novo'
      preLoaderRoute: typeof AuthenticatedPublicadorNovoRouteImport
      parentRoute: typeof AuthenticatedPublicadorRouteRoute
    }
    '/_authenticated/publicador/historico': {
      id: '/_authenticated/publicador/historico'
      path: '/historico'
      fullPath: '/publicador/historico'
      preLoaderRoute: typeof AuthenticatedPublicadorHistoricoRouteImport
      parentRoute: typeof AuthenticatedPublicadorRouteRoute
    }
    '/_authenticated/publicador/ajustes': {
      id: '/_authenticated/publicador/ajustes'
      path: '/ajustes'
      fullPath: '/publicador/ajustes'
      preLoaderRoute: typeof AuthenticatedPublicadorAjustesRouteImport
      parentRoute: typeof AuthenticatedPublicadorRouteRoute
    }
    '/api/public/hooks/webhook-instagram': {
      id: '/api/public/hooks/webhook-instagram'
      path: '/api/public/hooks/webhook-instagram'
      fullPath: '/api/public/hooks/webhook-instagram'
      preLoaderRoute: typeof ApiPublicHooksWebhookInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renovar-tokens': {
      id: '/api/public/hooks/renovar-tokens'
      path: '/api/public/hooks/renovar-tokens'
      fullPath: '/api/public/hooks/renovar-tokens'
      preLoaderRoute: typeof ApiPublicHooksRenovarTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publicar-posts': {
      id: '/api/public/hooks/publicar-posts'
      path: '/api/public/hooks/publicar-posts'
      fullPath: '/api/public/hooks/publicar-posts'
      preLoaderRoute: typeof ApiPublicHooksPublicarPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quitamany/conversa/$id': {
      id: '/_authenticated/quitamany/conversa/$id'
      path: '/conversa/$id'
      fullPath: '/quitamany/conversa/$id'
      preLoaderRoute: typeof AuthenticatedQuitamanyConversaIdRouteImport
      parentRoute: typeof AuthenticatedQuitamanyRouteRoute
    }
  }
}

interface AuthenticatedPublicadorRouteRouteChildren {
  AuthenticatedPublicadorAjustesRoute: typeof AuthenticatedPublicadorAjustesRoute
  AuthenticatedPublicadorHistoricoRoute: typeof AuthenticatedPublicadorHistoricoRoute
  AuthenticatedPublicadorNovoRoute: typeof AuthenticatedPublicadorNovoRoute
  AuthenticatedPublicadorIndexRoute: typeof AuthenticatedPublicadorIndexRoute
}

const AuthenticatedPublicadorRouteRouteChildren: AuthenticatedPublicadorRouteRouteChildren =
  {
    AuthenticatedPublicadorAjustesRoute: AuthenticatedPublicadorAjustesRoute,
    AuthenticatedPublicadorHistoricoRoute:
      AuthenticatedPublicadorHistoricoRoute,
    AuthenticatedPublicadorNovoRoute: AuthenticatedPublicadorNovoRoute,
    AuthenticatedPublicadorIndexRoute: AuthenticatedPublicadorIndexRoute,
  }

const AuthenticatedPublicadorRouteRouteWithChildren =
  AuthenticatedPublicadorRouteRoute._addFileChildren(
    AuthenticatedPublicadorRouteRouteChildren,
  )

interface AuthenticatedQuitamanyRouteRouteChildren {
  AuthenticatedQuitamanyAjustesRoute: typeof AuthenticatedQuitamanyAjustesRoute
  AuthenticatedQuitamanyAutomacoesRoute: typeof AuthenticatedQuitamanyAutomacoesRoute
  AuthenticatedQuitamanyContatosRoute: typeof AuthenticatedQuitamanyContatosRoute
  AuthenticatedQuitamanyIndexRoute: typeof AuthenticatedQuitamanyIndexRoute
  AuthenticatedQuitamanyConversaIdRoute: typeof AuthenticatedQuitamanyConversaIdRoute
}

const AuthenticatedQuitamanyRouteRouteChildren: AuthenticatedQuitamanyRouteRouteChildren =
  {
    AuthenticatedQuitamanyAjustesRoute: AuthenticatedQuitamanyAjustesRoute,
    AuthenticatedQuitamanyAutomacoesRoute:
      AuthenticatedQuitamanyAutomacoesRoute,
    AuthenticatedQuitamanyContatosRoute: AuthenticatedQuitamanyContatosRoute,
    AuthenticatedQuitamanyIndexRoute: AuthenticatedQuitamanyIndexRoute,
    AuthenticatedQuitamanyConversaIdRoute:
      AuthenticatedQuitamanyConversaIdRoute,
  }

const AuthenticatedQuitamanyRouteRouteWithChildren =
  AuthenticatedQuitamanyRouteRoute._addFileChildren(
    AuthenticatedQuitamanyRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPublicadorRouteRoute: typeof AuthenticatedPublicadorRouteRouteWithChildren
  AuthenticatedQuitamanyRouteRoute: typeof AuthenticatedQuitamanyRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPublicadorRouteRoute:
    AuthenticatedPublicadorRouteRouteWithChildren,
  AuthenticatedQuitamanyRouteRoute:
    AuthenticatedQuitamanyRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMetaCallbackRoute: ApiPublicMetaCallbackRoute,
  ApiPublicHooksPublicarPostsRoute: ApiPublicHooksPublicarPostsRoute,
  ApiPublicHooksRenovarTokensRoute: ApiPublicHooksRenovarTokensRoute,
  ApiPublicHooksWebhookInstagramRoute: ApiPublicHooksWebhookInstagramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
