/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedNovoRouteImport } from './routes/_authenticated/novo'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as ApiPublicMetaCallbackRouteImport } from './routes/api/public/meta-callback'
import { Route as AuthenticatedConversaIdRouteImport } from './routes/_authenticated/conversa.$id'
import { Route as ApiPublicHooksWebhookInstagramRouteImport } from './routes/api/public/hooks/webhook-instagram'
import { Route as ApiPublicHooksRenovarTokensRouteImport } from './routes/api/public/hooks/renovar-tokens'
import { Route as ApiPublicHooksPublicarPostsRouteImport } from './routes/api/public/hooks/publicar-posts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNovoRoute = AuthenticatedNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMetaCallbackRoute = ApiPublicMetaCallbackRouteImport.update({
  id: '/api/public/meta-callback',
  path: '/api/public/meta-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversaIdRoute = AuthenticatedConversaIdRouteImport.update({
  id: '/conversa/$id',
  path: '/conversa/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksWebhookInstagramRoute =
  ApiPublicHooksWebhookInstagramRouteImport.update({
    id: '/api/public/hooks/webhook-instagram',
    path: '/api/public/hooks/webhook-instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRenovarTokensRoute =
  ApiPublicHooksRenovarTokensRouteImport.update({
    id: '/api/public/hooks/renovar-tokens',
    path: '/api/public/hooks/renovar-tokens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublicarPostsRoute =
  ApiPublicHooksPublicarPostsRouteImport.update({
    id: '/api/public/hooks/publicar-posts',
    path: '/api/public/hooks/publicar-posts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/conversa/$id': typeof AuthenticatedConversaIdRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/hooks/publicar-posts': typeof ApiPublicHooksPublicarPostsRoute
  '/api/public/hooks/renovar-tokens': typeof ApiPublicHooksRenovarTokensRoute
  '/api/public/hooks/webhook-instagram': typeof ApiPublicHooksWebhookInstagramRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/conversa/$id': typeof AuthenticatedConversaIdRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/hooks/publicar-posts': typeof ApiPublicHooksPublicarPostsRoute
  '/api/public/hooks/renovar-tokens': typeof ApiPublicHooksRenovarTokensRoute
  '/api/public/hooks/webhook-instagram': typeof ApiPublicHooksWebhookInstagramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/novo': typeof AuthenticatedNovoRoute
  '/_authenticated/conversa/$id': typeof AuthenticatedConversaIdRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/hooks/publicar-posts': typeof ApiPublicHooksPublicarPostsRoute
  '/api/public/hooks/renovar-tokens': typeof ApiPublicHooksRenovarTokensRoute
  '/api/public/hooks/webhook-instagram': typeof ApiPublicHooksWebhookInstagramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/automacoes'
    | '/contatos'
    | '/conversas'
    | '/historico'
    | '/novo'
    | '/conversa/$id'
    | '/api/public/meta-callback'
    | '/api/public/hooks/publicar-posts'
    | '/api/public/hooks/renovar-tokens'
    | '/api/public/hooks/webhook-instagram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/automacoes'
    | '/contatos'
    | '/conversas'
    | '/historico'
    | '/novo'
    | '/conversa/$id'
    | '/api/public/meta-callback'
    | '/api/public/hooks/publicar-posts'
    | '/api/public/hooks/renovar-tokens'
    | '/api/public/hooks/webhook-instagram'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/automacoes'
    | '/_authenticated/contatos'
    | '/_authenticated/conversas'
    | '/_authenticated/historico'
    | '/_authenticated/novo'
    | '/_authenticated/conversa/$id'
    | '/api/public/meta-callback'
    | '/api/public/hooks/publicar-posts'
    | '/api/public/hooks/renovar-tokens'
    | '/api/public/hooks/webhook-instagram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMetaCallbackRoute: typeof ApiPublicMetaCallbackRoute
  ApiPublicHooksPublicarPostsRoute: typeof ApiPublicHooksPublicarPostsRoute
  ApiPublicHooksRenovarTokensRoute: typeof ApiPublicHooksRenovarTokensRoute
  ApiPublicHooksWebhookInstagramRoute: typeof ApiPublicHooksWebhookInstagramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/novo': {
      id: '/_authenticated/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof AuthenticatedNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/meta-callback': {
      id: '/api/public/meta-callback'
      path: '/api/public/meta-callback'
      fullPath: '/api/public/meta-callback'
      preLoaderRoute: typeof ApiPublicMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversa/$id': {
      id: '/_authenticated/conversa/$id'
      path: '/conversa/$id'
      fullPath: '/conversa/$id'
      preLoaderRoute: typeof AuthenticatedConversaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/webhook-instagram': {
      id: '/api/public/hooks/webhook-instagram'
      path: '/api/public/hooks/webhook-instagram'
      fullPath: '/api/public/hooks/webhook-instagram'
      preLoaderRoute: typeof ApiPublicHooksWebhookInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renovar-tokens': {
      id: '/api/public/hooks/renovar-tokens'
      path: '/api/public/hooks/renovar-tokens'
      fullPath: '/api/public/hooks/renovar-tokens'
      preLoaderRoute: typeof ApiPublicHooksRenovarTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publicar-posts': {
      id: '/api/public/hooks/publicar-posts'
      path: '/api/public/hooks/publicar-posts'
      fullPath: '/api/public/hooks/publicar-posts'
      preLoaderRoute: typeof ApiPublicHooksPublicarPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedNovoRoute: typeof AuthenticatedNovoRoute
  AuthenticatedConversaIdRoute: typeof AuthenticatedConversaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedNovoRoute: AuthenticatedNovoRoute,
  AuthenticatedConversaIdRoute: AuthenticatedConversaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMetaCallbackRoute: ApiPublicMetaCallbackRoute,
  ApiPublicHooksPublicarPostsRoute: ApiPublicHooksPublicarPostsRoute,
  ApiPublicHooksRenovarTokensRoute: ApiPublicHooksRenovarTokensRoute,
  ApiPublicHooksWebhookInstagramRoute: ApiPublicHooksWebhookInstagramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
